[package]
authors = ["Walfie <walfington@gmail.com>"]
name = "petronel"
version = "0.1.0"

[dependencies]
chrono = "0.4"
error-chain = "0.10.0"
futures = "0.1"
lazy_static = "0.2"
regex = "0.2"
tokio-core = "0.1"
twitter-stream = "0.5"
