[package]
name = "petronel"
version = "0.1.0"
authors = ["walfie <walfington@gmail.com>"]

[dependencies]
futures = "0.1.18"
serde_json = "1.0.9"
serde_derive = "1.0.27"
serde = "1.0.27"
regex = "0.2.6"

[dependencies.chrono]
version = "0.4"
features = ["serde"]
